version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: books_db
    restart: always
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: franckdollar91
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  scraper:
    build:
      context: .  # Le contexte est le répertoire racine du projet
      dockerfile: Scraper/Dockerfile
    container_name: scraper
    depends_on:
      - database

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  webapp:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    container_name: webapp
    ports:
      - "8050:8050"
    depends_on:
      - api

  db_initializer:
    build:
      context: .
      dockerfile: Database/Dockerfile
    container_name: db_initializer
    depends_on:
      - database
    entrypoint: ["/bin/sh", "-c", "sleep 10 && python /app/database.py"]

volumes:
  db_data: