version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: franckdollar91
    ports:
      - "5432:5432"
    volumes:
      - projet_scraping_imdb_postgres_data:/var/lib/postgresql/data
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # ✅ Monte le fichier SQL

  scraper:
    build: ./Scraper
    container_name: scraper
    depends_on:
      - postgres_db
    command: ["python", "scraper.py"]

  api:
    build: ./API
    container_name: flask_api
    depends_on:
      - postgres_db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:franckdollar91@postgres_db:5432/books_db"
    command: ["python", "api.py"]

volumes:
  projet_scraping_imdb_postgres_data:
